#server config
#<----------------------------->
server:
  port: 8080
#spring config
#<----------------------------->
spring:
  application:
    name: iot-lab
  output:
    ansi:
      enabled: always
#mqtt config
#<----------------------------->
mqtt:
  serverUris: tcp://192.168.0.101:1883
  username: admin
  password: admin
  topicsToRead: '#'
  topicsToSend: offRosette, onRosette